#!/bin/bash
#
# Creates common directories in HOME.

set -e
PROGRAM_NAME=$(basename "$0")
CREATED_COMMON_DIR=
DIR_NAMES_TO_CREATE=(
    "books"
    "git"
    "hg"
    "src"
    "svn"
)

for dirname in "${DIR_NAMES_TO_CREATE[@]}"; do 
    if ! [ -d "${HOME}/$dirname" ]; then
        CREATED_COMMON_DIR="true"
        # HOME should already exist
        mkdir "${HOME}/$dirname"
    fi
done

if [ -n "$CREATED_COMMON_DIR" ]; then echo -e "$SUCCESS common directories were created"; fi

exit 0
