#!/bin/bash
#
# Installs different 'binaries' (or scripts) a global location 
# common in the PATH.

set -e
PROGRAM_NAME=$(basename "$0")
GLOBAL_BIN_PATH="/usr/local/bin/"
GENERAL_PURPOSE_SCRIPTS="general-purpose-scripts"
declare -A GIT_REPO_URLS=(
    ["$GENERAL_PURPOSE_SCRIPTS"]=https://github.com/cavcrosby/general-purpose-scripts
)

# NOTES: check to see if I am root. Will want to be root before checking
# anything else (e.g. I could have GIT_REPOS_PATH defined as some user
# but not root).
ROOT_ID=0
if [ "$(id --user)" != "$ROOT_ID" ]; then
    echo "${PROGRAM_NAME}: must be root to run script"
    exit 1
fi

if [ -z "$GIT_REPOS_PATH" ]; then
    echo "${PROGRAM_NAME}: GIT_REPOS_PATH does not exist in env for root"
    exit 1
fi

if [ -z "$(which git)" ]; then
    echo "${PROGRAM_NAME}: git cannot be found on the PATH!"
    exit 1
fi

cd "$GIT_REPOS_PATH" || exit 1

for git_repo_url in "${!GIT_REPO_URLS[@]}"; do
    case "$git_repo_url" in
        "${GENERAL_PURPOSE_SCRIPTS}")   if ! [ -d "$GENERAL_PURPOSE_SCRIPTS" ]; then 
                                            git clone --quiet "${GIT_REPO_URLS["$GENERAL_PURPOSE_SCRIPTS"]}" "$GENERAL_PURPOSE_SCRIPTS" 
                                        fi
                                        sudo install --mode=755 "./${GENERAL_PURPOSE_SCRIPTS}/pathjoin" "$GLOBAL_BIN_PATH"
                                        ;;
    esac
done

echo -e "$SUCCESS global binaries were installed"

exit 0
