#!/bin/bash
#
# Installs different 'binaries' (or scripts) a local location 
# common in the PATH.

set -e
PROGRAM_NAME=$(basename "$0")
LOCAL_BIN_PATH="${HOME}/.local/bin"
GENERAL_PURPOSE_SCRIPTS="general-purpose-scripts"
LINK_SCRIPTS_FROMDIR="link-scripts-fromdir"
declare -A GIT_REPO_URLS=(
    ["$GENERAL_PURPOSE_SCRIPTS"]=https://github.com/reap2sow1/general-purpose-scripts
)

if [ -z "$(which git)" ]; then
    echo "${PROGRAM_NAME}: git cannot be found on the PATH!"
    exit 1
fi

if ! [ -d "$LOCAL_BIN_PATH" ]; then
    mkdir --parents "$LOCAL_BIN_PATH"
fi

cd "$GIT_REPOS_PATH" || exit 1

for git_repo_url in "${!GIT_REPO_URLS[@]}"; do
    case "$git_repo_url" in
        "${GENERAL_PURPOSE_SCRIPTS}")   if ! [ -d "$GENERAL_PURPOSE_SCRIPTS" ]; then 
                                            git clone --quiet "${GIT_REPO_URLS["$GENERAL_PURPOSE_SCRIPTS"]}" "$GENERAL_PURPOSE_SCRIPTS" 
                                        fi
                                        # NOTE: link-scripts-fromdir creates symlinks (fromdir) to scripts in 
                                        # GENERAL_PURPOSE_SCRIPTS repo
                                        if [ -x "./${GENERAL_PURPOSE_SCRIPTS}/${LINK_SCRIPTS_FROMDIR}" ]; then
                                            cd "$GENERAL_PURPOSE_SCRIPTS" || exit 1
                                            # i'm ok with LINK_DIR value being nonquoted here
                                            sed --in-place "s|LINK_DIR=|LINK_DIR=${LOCAL_BIN_PATH}|" "./${LINK_SCRIPTS_FROMDIR}"
                                            "./${LINK_SCRIPTS_FROMDIR}"
                                            cd ..
                                        fi
                                        ;;
    esac
done

echo -e "$SUCCESS local binaries were installed"

exit 0
