#!/bin/bash
#
# Installs shellfuncs https://github.com/reap2sow1/shellfuncs.

set -e
PROGRAM_NAME=$(basename "$0")
SHELLFUNCS_INSTALL_PROGRAM_URL="https://raw.githubusercontent.com/reap2sow1/shellfuncs/main/install"
SHELLFUNCS_INSTALL_PROGRAM_NAME="install"
export SHELLFUNCS_AUTOMATED_INSTALL="y"

if [ -z "$(which curl)" ]; then
    echo "${PROGRAM_NAME}: curl cannot be found on the PATH!"
    exit 1
fi

# NOTES: this env var is set during the shellfuncs install.
# If its set, then we don't want todo a reinstall.
if [ -z "$SHELLFUNCS_REPO_PATH" ]; then
    curl --output "$SHELLFUNCS_INSTALL_PROGRAM_NAME" --silent "$SHELLFUNCS_INSTALL_PROGRAM_URL"
    chmod 755 "$SHELLFUNCS_INSTALL_PROGRAM_NAME"
    if ! ./"${SHELLFUNCS_INSTALL_PROGRAM_NAME}" > /dev/null 2>&1; then
        echo "$ERROR something went wrong with the shellfuncs install!"
        exit 1
    fi
fi

echo -e "$SUCCESS 'shellfuncs' was installed"

exit 0
