---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: \.git-credentials\.shtpl

      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/koalaman/shellcheck-precommit.git
    rev: v0.11.0
    hooks:
      - id: shellcheck
