#!/bin/bash
#
# Small setup script for dotfiles repo.
# Usage: curl --silent https://raw.githubusercontent.com/cavcrosby/dotfiles/main/install | bash

set -e
PROGRAM_NAME="install"
PROFILE_FILE_NAME=".profile" # assuming .profile is ALWAYS '.profile'
TEMP_DIR_NAME="${PROGRAM_NAME}-temp"
PROFILE_REMOTE_URL='https://raw.githubusercontent.com/cavcrosby/dotfiles/main/.profile'
DOTFILES_TO_INCLUDE=(
    .bashrc
    .profile
    .bash_profile
    .gitignore
    .gitconfig
    .msmtprc
    .config/VSCodium/User/settings.json
    .ssh/authorized_keys
    .ssh/config
)

if [ "$PWD" != "$HOME" ]; then
    # main reason is to avoid filemode permissions issues
    echo "${PROGRAM_NAME}: re-run this script in $HOME (assuming you haven't changed this!), to run this correctly"
    exit 1
fi

if [ -z "$(which curl)" ]; then
    echo "${PROGRAM_NAME}: curl cannot be found on the PATH!"
    exit 1
fi

if [ -z "$(which git)" ]; then
    echo "${PROGRAM_NAME}: git cannot be found on the PATH!"
    exit 1
fi

mkdir "$TEMP_DIR_NAME" || exit 1
cd "$TEMP_DIR_NAME" || exit 1

# --fail just means to 'fail' silently without a http status code
if ! curl --silent --fail "$PROFILE_REMOTE_URL" --output "$PROFILE_FILE_NAME"; then
    echo "${PROGRAM_NAME}: could not fetch $PROFILE_FILE_NAME from url!"
    exit 1
fi

# shellcheck disable=SC1090
source "./${PROFILE_FILE_NAME}"
rm "./${PROFILE_FILE_NAME}"
cd ..
rmdir "$TEMP_DIR_NAME"

if [ -z "$GIT_REPOS_PATH" ]; then
    echo "${PROGRAM_NAME}: GIT_REPOS_PATH was not imported from .profile"
    exit 1
elif ! [ -d "$GIT_REPOS_PATH" ]; then 
    mkdir --parents "$GIT_REPOS_PATH"
fi

LOCAL_REPO_PATH="${GIT_REPOS_PATH}/${DOTFILES_REPO_NAME}"
INIT_SCRIPTS_PATH="${LOCAL_REPO_PATH}/init"

# shellcheck disable=2034
read -r -p "Is this a reinstall, y/n? (n) " RE_INSTALL_REPLY <&1

# using parameter expansion, ',,' append will convert the string to lowercase
if [ "${RE_INSTALL_REPLY,,}" == "y" ]; then
    if ! [ -d "$LOCAL_REPO_PATH" ]; then
        echo "$ERROR the $DOTFILES_REPO_NAME cannot be found on the local file system"
        exit 1
    fi
    cd "$LOCAL_REPO_PATH"
    git stash push --quiet
    git pull --quiet
    git stash pop --quiet
    cd - > /dev/null
else
    git clone --quiet "$DOTFILES_REMOTE_REPO_URL" "$LOCAL_REPO_PATH" > /dev/null
fi

# dotfiles may exist in other directories, so we want to make sure the parent directories
# exist before placing down the target link
# NOTES: check and make sure the dotfile is in DOTFILES_TO_INCLUDE
# or else the particular dotfile will not be linked at install! Also,
# dirname may return a literal '.' char.
for dotfile in "${DOTFILES_TO_INCLUDE[@]}"; do
    if [ "$(dirname "$dotfile")" != "." ]; then
        mkdir --parents "$(dirname "$dotfile")"
    fi
    ln --symbolic --force "${LOCAL_REPO_PATH}/${dotfile}" "./${dotfile}"
done

# NOTES: init scripts should be limited in scope to configure the new 
# system. Reinstall behavior varies from script to script (based on
# desired output). Package installs (e.g. deb, rpm) should be avoided.
# shellcheck disable=SC1091
for f in "${INIT_SCRIPTS_PATH}"/*
do
    case "$f" in
        "${INIT_SCRIPTS_PATH}/install-globalbins")      . "${INIT_SCRIPTS_PATH}/.env"
                                                        if [ -n "$SUDOER_PASSWORD" ]; then 
                                                            echo "$SUDOER_PASSWORD" | sudo --stdin --preserve-env=GIT_REPOS_PATH,SUCCESS "$f"
                                                        else
                                                            echo -e "${PROGRAM_NAME}: SUDOER_PASSWORD not set, run $(basename "$f") manually, e.g."
                                                            echo "echo \$SUDOER_PASSWORD | sudo --stdin --preserve-env=GIT_REPOS_PATH,SUCCESS \$f"
                                                        fi
                                                        ;;
        *)                                              "$f"
                                                        ;;
    esac
done

echo -e "$SUCCESS installation was successfull! Restart your shell session to pull in new configurations"
